### ISSUE TITLE
Bug + thank you for this library!

### ISSUE THREAD

**Issue by oferRounds** [enzomanuelmangano/pressto#7]
Getting multiple warning and screen frizzes:

```
Reanimated] Reading from `value` during component render. Please ensure that you do not access the `value` property or use `get` method of a shared value while React is rendering a component.

If you don't want to see this message, you can disable the `strict` mode. Refer to:
https://docs.swmansion.com/react-native-reanimated/docs/debugging/logger-configuration for more details.
```

**Comment by oferRounds** [comment]
<img width="1227" alt="image" src="https://github.com/user-attachments/assets/d98d63a7-98e2-4262-8225-bc5ca61436bb" />

**Comment by enzomanuelmangano** [comment]
Hey @oferRounds thanks a lot for reporting the issue. I just released a beta version with the fix (here's the PR https://github.com/enzomanuelmangano/pressto/pull/8). 
You can give a quick try by running: 
```
yarn add pressto@0.2.1-beta.0
```

Please let me know if the version works properly for your use case!

**Comment by oferRounds** [comment]
@enzomanuelmangano thank you for this!
Although I do see the warning is now gone (after upgrading), it seems something with `Pressto` causes my JS thread to get blocked. Didn’t have enough time yet to get more details, but this is what I see so for

**Comment by enzomanuelmangano** [comment]
Thanks for the feedback, @oferRounds! I'll close this issue for now and release the 0.2.1 with the fix, but feel free to open a new one or DM me on [Twitter](https://x.com/reactiive_) with a video of the new issue you're experiencing

**Comment by oferRounds** [comment]
sure, thank you!
